import './globals.css'
import { Inter, Playfair_Display } from 'next/font/google'
import { ApolloWrapper } from '@/lib/apollo-wrapper'
import Providers from './components/auth/Providers'

const inter = Inter({ subsets: ['latin'] })

export const playfair_display = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={playfair_display.className}>
      <Providers>
        <ApolloWrapper>
            {children}
          </ApolloWrapper>
        </Providers>
      </body>
    </html>
  )
}
